### ISSUE TITLE
Decide - Font

### ISSUE THREAD

**Issue by larson-carter** [MLH-Fellowship/MLH-OH-MY-ZSH-THEME#3]
Decide what font/s that we want to utilize in this theme.

**Comment by smartclash** [comment]
How about we use a font that has support for Font Ligature? Like Fira Code?

**Comment by OPARA-PROSPER** [comment]
I'll suggest we work with the official MLH branding fonts same way we are using the MLH colors,.

I'm not sure but I think MLH should have specific fonts they use for flyers.

@jonmarkgo could prolly help us with that info

**Comment by jonmarkgo** [comment]
We use a lot of Open Sans, but not sure how that'd look in a terminal.
