### ISSUE TITLE
DECIDE - Enabled Plugins

### ISSUE THREAD

**Issue by larson-carter** [MLH-Fellowship/MLH-OH-MY-ZSH-THEME#6]
What plugins do we want to enable with this theme?

What is useful at hackathon?

Git, ZSH-AUTOCOMPLETE, etc?

**Comment by bartekpacia** [comment]
Do we want to do this? Personally, I'd be annoyed if the theme was adding its own stuff to my config.

**Comment by larson-carter** [comment]
@bartekpacia I wasn't thinking about adding anything too crazy. Mainly just Git, and ZSH Autocomplete?

**Comment by bartekpacia** [comment]
The basic one would be great.

**Comment by AlbertoPdRF** [comment]
Giving feedback here as asked by @larson-carter: I'm using the plugins that come with Oh My Zsh by default and I personally wouldn't like a theme to change that.
